version: "3.8"

services:
  web:
    depends_on: 
      - api
    image: piumikavindya/motor-service-and-wash-web-frontend:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5555

  api:
    depends_on: 
      - db
    image: piumikavindya/motor-service-and-wash-web-backend:${BUILD_NUMBER}
    ports: 
      - "5555:5555"
    environment: 
      DB_URL: mongodb://db:27017/MotorServiceAndWashCentreApp

  db:
    image: piumikavindya/motor-service-and-wash-web-database:${BUILD_NUMBER}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
