version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5555
    volumes:
      - ./frontend:/app

  api:
    depends_on: 
      - db
    build: ./backend
    ports: 
      - "5555:5555"
    environment: 
      DB_URL: mongodb://db:27017/MotorServiceAndWashCentreApp
    volumes:
      - ./backend:/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: